# Generated by Django 3.0.8 on 2020-07-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_remove_destination_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='img',
            field=models.ImageField(default='destination_1.jpg', upload_to='pics'),
        ),
    ]
