# Generated by Django 3.0.8 on 2020-07-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_destination_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(default='calicut.jpeg', upload_to='pics'),
        ),
    ]
